refactor. this must lead to error

diff --git a/.github/workflows/etl_pipeline.yaml b/.github/workflows/etl_pipeline.yaml
--- a/.github/workflows/etl_pipeline.yaml
+++ b/.github/workflows/etl_pipeline.yaml
@@ -34,7 +34,14 @@ jobs:
     
     - name: Verify network
       shell: bash
-      run: docker network ls
+      run: |
+        NET_DATA=$(docker network ls --filter "NAME=test_net011" --format json | jq)
+        if [[ $NET_DATA == "" ]]; then 
+          echo "Network not found"
+          exit 1; 
+        else 
+          echo "$NET_DATA"
+        fi
     
     - name: Create MySQL .env
       shell: bash
@@ -50,10 +57,6 @@ jobs:
       working-directory: ./infra/mysql
       run: docker compose up --build -d
     
-    - name: Verify MySQL
-      shell: bash
-      run: docker ps # && sleep 40 && docker ps
-    
 #    - name: Test MySQL CLI in container
 #      shell: bash
 #      run: |
@@ -66,23 +69,13 @@ jobs:
         echo "CLICKHOUSE_USER=${{ secrets.CLICKHOUSE_USER }}" >> .env
         echo "CLICKHOUSE_PASSWORD=${{ secrets.CLICKHOUSE_PASSWORD }}" >> .env
 
-    - name: Verify .env
-      working-directory: ./infra/clickhouse
-      shell: bash
-      run: ls -l .env
-
     - name: Clickhouse docker compose
       shell: bash
       working-directory: ./infra/clickhouse
       run: |
         docker compose up --build -d
     
-    - name: Verify Clickhouse
-      shell: bash
-      run: |
-        docker ps
-    
-    - name: Create .env
+    - name: Create .env for ecommerce
       working-directory: ./services/static-ecommerce
       shell: bash
       run: |
@@ -91,21 +84,6 @@ jobs:
         echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
         echo $MYSQL_HOST >> .env
         echo $MYSQL_PORT >> .env
-    
-    - name: Bulid ecommerce
-      shell: bash
-      working-directory: ./services/static-ecommerce
-      run: |
-        docker build -t $DATA_SOURCE_IMG .
-    
-    - name: Run ecommerce
-      shell: bash
-      working-directory: ./services/static-ecommerce
-      run: |
-        docker run \
-          --network $NETWORK_NAME \
-          --env-file .env \
-          $DATA_SOURCE_IMG --user 2 --product 3 --order 5
     
     - name: Create .env for ETL
       working-directory: ./services/etl
@@ -121,11 +99,26 @@ jobs:
         echo $CLICKHOUSE_HOST >> .env
         echo 4CLICKHOUSE_PORT >> .env
     
+    - name: Bulid ecommerce
+      shell: bash
+      working-directory: ./services/static-ecommerce
+      run: |
+        docker build -t $DATA_SOURCE_IMG .
+    
     - name: Bulid ETL
       shell: bash
       working-directory: ./services/etl
       run: |
         docker build -t $ETL_IMG .
+    
+    - name: Run ecommerce
+      shell: bash
+      working-directory: ./services/static-ecommerce
+      run: |
+        docker run \
+          --network $NETWORK_NAME \
+          --env-file .env \
+          $DATA_SOURCE_IMG --user 2 --product 3 --order 5
     
     - name: Run ETL
       shell: bash
