updated to new reporter

diff --git a/.github/workflows/sample-pipeline.yaml b/.github/workflows/sample-pipeline.yaml
--- a/.github/workflows/sample-pipeline.yaml
+++ b/.github/workflows/sample-pipeline.yaml
@@ -13,17 +13,30 @@ concurrency:
 
 jobs:
   data-pipeline:
+    env:
+      REPORTER_IMG: "reporter:latest"
+      NETWORK_NAME: analytics_network
+      CLICKHOUSE_HOST: clickhouse_server
+      CLICKHOUSE_PORT: 8123
+
     runs-on: ubuntu-22.04
     steps:
     - uses: actions/checkout@v4
 
     - name: Create docker network
       shell: bash
-      run: docker network create --attachable --driver bridge analytics_network
+      run: docker network create --attachable --driver bridge $NETWORK_NAME
     
     - name: Verify network
       shell: bash
-      run: docker network ls
+      run: |
+        NET_DATA=$(docker network ls --filter "NAME=$NETWORK_NAME" --format json | jq)
+        if [[ $NET_DATA == "" ]]; then 
+          echo "Network not found"
+          exit 1; 
+        else 
+          echo "$NET_DATA"
+        fi
     
     - name: Create .env file for Clickhouse
       working-directory: ./infra/clickhouse
@@ -58,8 +71,8 @@ jobs:
       working-directory: ./utils/banner-data
       shell: bash
       run: |
-        echo "CLICKHOUSE_HOST=clickhouse_server" >> .env
-        echo "CLICKHOUSE_PORT=8123" >> .env
+        echo "CLICKHOUSE_HOST=$CLICKHOUSE_HOST" >> .env
+        echo "CLICKHOUSE_PORT=$CLICKHOUSE_PORT" >> .env
         echo "CLICKHOUSE_USER=${{ secrets.CLICKHOUSE_USER }}" >> .env
         echo "CLICKHOUSE_PASSWORD=${{ secrets.CLICKHOUSE_PASSWORD }}" >> .env
 
@@ -69,23 +82,56 @@ jobs:
       run: |
         chmod +x ./run.sh && ./run.sh
     
-    - name: Bulid reporter
+    - name: Bulid Reporter
       shell: bash
       working-directory: ./services/reporter
       run: |
-        chmod +x ./build.sh && ./build.sh
+        docker build -t $REPORTER_IMG .
     
     - name: Create .env for reporter
       working-directory: ./services/reporter
       shell: bash
       run: |
-        echo "CLICKHOUSE_HOST=clickhouse_server" >> .env
-        echo "CLICKHOUSE_PORT=8123" >> .env
+        echo "CLICKHOUSE_HOST=$CLICKHOUSE_HOST" >> .env
+        echo "CLICKHOUSE_PORT=$CLICKHOUSE_PORT" >> .env
         echo "CLICKHOUSE_USER=${{ secrets.CLICKHOUSE_USER }}" >> .env
         echo "CLICKHOUSE_PASSWORD=${{ secrets.CLICKHOUSE_PASSWORD }}" >> .env
     
-    - name: Run reporter
+    - name: Checking databases
       shell: bash
-      working-directory: ./services/reporter
       run: |
-        chmod +x ./run.sh && ./run.sh
+        echo "CLICKHOUSE_HOST=$CLICKHOUSE_HOST" >> check.env
+        echo "CLICKHOUSE_PORT=$CLICKHOUSE_PORT" >> check.env
+        echo "CLICKHOUSE_USER=${{ secrets.CLICKHOUSE_USER }}" >> check.env
+        echo "CLICKHOUSE_PASSWORD=${{ secrets.CLICKHOUSE_PASSWORD }}" >> check.env
+        timeout 60s bash -c '
+        until
+          source check.env;
+          curl -s \
+            -H "X-ClickHouse-User: $CLICKHOUSE_USER" \
+            -H "X-ClickHouse-Key: $CLICKHOUSE_PASSWORD" \
+            --data "SELECT 1;" \
+            "http://localhost:$CLICKHOUSE_PORT/" | grep -q "1"; 
+            do
+              echo "Waiting for ClickHouse";
+              sleep 2;
+            done;
+        '
+    
+    - name: Run reporter in clickhouse
+      shell: bash
+      run: | 
+        echo "CLICKHOUSE_HOST=$CLICKHOUSE_HOST" >> reporter.env
+        echo "CLICKHOUSE_PORT=$CLICKHOUSE_PORT" >> reporter.env
+        echo "CLICKHOUSE_USER=${{ secrets.CLICKHOUSE_USER }}" >> reporter.env
+        echo "CLICKHOUSE_PASSWORD=${{ secrets.CLICKHOUSE_PASSWORD }}" >> reporter.env
+        docker run \
+          --network analytics_network \
+          --env-file reporter.env \
+          --volume ./services/reporter/data/:/data \
+          $REPORTER_IMG --config '
+            {
+              "driver": "clickhouse", 
+              "query": "SELECT * FROM cicd_test_event_db.banner_view LIMIT 100"
+            }
+          '
